// <auto-generated />
using System;
using Balalbookapi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balalbookapi.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Balalbookapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Blender_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Blender_Name");

                    b.Property<string>("Book_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Book_Name");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("Balalbookapi.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Book_Id")
                        .HasColumnType("int")
                        .HasColumnName("Book_Id");

                    b.Property<DateTime>("date_from_star")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_from_star");

                    b.Property<DateTime>("date_to_end")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_to_end");

                    b.HasKey("Id");

                    b.HasIndex("Book_Id");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("Balalbookapi.Models.Reservation", b =>
                {
                    b.HasOne("Balalbookapi.Models.Book", "book")
                        .WithMany()
                        .HasForeignKey("Book_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("book");
                });
#pragma warning restore 612, 618
        }
    }
}
